version: "3"

services:
  devias-kit:
    image: devias-kit
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3002:3000
    volumes:
      # mount current dir into docker container
      - ./:/usr/src/app
      # ignore local node_modules, use container
      - /usr/src/app/node_modules